name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Check and update dependencies
      run: |
        pip install -r requirements.txt
        python src/main.py check
        python src/main.py update-all 